/*
 * Copyright (C) 2023-2026 HyperCeiler Contributions
 * Copyright (C) 2026 YGHFv
 * SPDX-License-Identifier: AGPL-3.0-or-later
 */
package io.github.YGHFv.HyperExtend.core

val SYSTEM_UI_FEATURES: List<HyperFeature> = listOf(
    HyperFeature(
        id = "control_center_hide_edit",
        title = "隐藏控制中心编辑按钮",
        summary = "从新版控制中心列表中移除编辑入口",
        scopes = listOf("systemui"),
        origin = "西米露 / HyperCeiler · HideEditButton",
        license = "AGPL-3.0",
        defaultEnabled = false,
        group = ScopeFeatureGroup.CONTROL_CENTER,
        requirement = "已静态核验控制中心插件 183022200，待真机验收。仅隐藏入口，不禁止编辑能力；需要编辑时关闭本开关并重启系统界面。",
    ),
    HyperFeature(
        id = "volume_hide_collapsed_footer",
        title = "隐藏折叠音量面板底部按钮",
        summary = "折叠时隐藏静音和勿扰按钮，保留展开入口",
        scopes = listOf("systemui"),
        origin = "西米露 / HyperCeiler · HideCollpasedFootButton",
        license = "AGPL-3.0",
        defaultEnabled = false,
        group = ScopeFeatureGroup.CONTROL_CENTER,
        requirement = "展开后遵循宿主原有按钮显示条件，不关闭静音或勿扰。已静态核验音量插件 183022200，待真机验收；修改后重启系统界面生效。",
    ),
    HyperFeature(
        id = NotificationExpansionSettings.EXPAND,
        title = "自动展开指定应用通知",
        summary = "自动展开通知内容和固定悬浮通知",
        scopes = listOf("systemui"),
        origin = "西米露 / HyperCeiler · ExpandNotificationKt",
        license = "AGPL-3.0",
        defaultEnabled = false,
        group = ScopeFeatureGroup.CONTROL_CENTER,
        config = listOf(HyperText(NotificationExpansionSettings.PACKAGES, "应用包名", "以空格、逗号或换行分隔；空名单不生效")),
        requirement = "保留手动收起、锁屏和敏感内容限制；仅展开系统允许展开的内容，不创建悬浮通知。修改后重启系统界面生效，待真机验收。",
    ),
    HyperFeature(
        id = NotificationExpansionSettings.COLLAPSE,
        title = "自动收起展开的悬浮通知",
        summary = "展开后按设定时间结束悬浮显示，不删除通知",
        scopes = listOf("systemui"),
        origin = "西米露 / HyperCeiler · AutoDismissExpandedPopupsHook",
        license = "AGPL-3.0",
        defaultEnabled = false,
        group = ScopeFeatureGroup.CONTROL_CENTER,
        config = listOf(NotificationExpansionSettings.timeout),
        requirement = "锁屏、正在快捷回复、通知菜单和全屏来电等提醒不自动收起；系统延长提醒使用 10 秒。修改后重启系统界面生效，待真机验收。",
    ),
    HyperFeature(
        id = "control_center_hide_carrier",
        title = "隐藏控制中心运营商名称",
        summary = "只隐藏运营商区域，保留隐私提示",
        scopes = listOf("systemui"),
        origin = "西米露 / HyperCeiler · CustomCarrierText",
        license = "AGPL-3.0",
        defaultEnabled = false,
        group = ScopeFeatureGroup.CONTROL_CENTER,
        requirement = "仅迁移隐藏名称模式，不含去分隔符、设备名称替换或隐藏 HD 图标；保留麦克风、相机、定位等隐私提示与布局占位。修改后重启系统界面生效，待真机验收。",
    ),
    HyperFeature(
        id = MediaCardSettings.LAYOUT,
        title = "媒体卡片布局",
        summary = "调整专辑封面、操作顺序和标题间距",
        scopes = listOf("systemui"),
        origin = "西米露 / HyperCeiler · MediaViewLayout",
        license = "AGPL-3.0",
        defaultEnabled = false,
        group = ScopeFeatureGroup.CONTROL_CENTER,
        options = listOf(
            HyperOption(MediaCardSettings.LEFT_ALIGNED, "操作按钮靠左", defaultEnabled = false),
            HyperOption(MediaCardSettings.HIDE_SEAMLESS, "隐藏音频输出切换入口", defaultEnabled = false),
        ),
        config = listOf(
            HyperChoice(MediaCardSettings.ALBUM, "专辑封面", listOf(
                ChoiceEntry("0", "系统默认"), ChoiceEntry("1", "隐藏应用角标"), ChoiceEntry("2", "隐藏封面与角标"),
            )),
            HyperChoice(MediaCardSettings.ORDER, "操作按钮顺序", listOf(
                ChoiceEntry("0", "系统默认"), ChoiceEntry("1", "1 · 2 · 3 · 0 · 4"), ChoiceEntry("2", "2 · 1 · 3 · 0 · 4"),
            ), summary = "数字为系统原始按钮位置，从 0 开始；仅重排位置，不改变操作和无障碍标签"),
            MediaCardSettings.titleMargin,
            MediaCardSettings.artistMargin,
        ),
        requirement = "仅调整通知中心普通媒体卡片，保留翻折外屏、灵动岛和播放控制；隐藏输出入口不停止投放。默认选项保留系统布局。修改后重启系统界面生效。",
    ),
    HyperFeature(
        id = MediaCardSettings.TEXT_SIZE,
        title = "媒体卡片字号",
        summary = "分别设置标题、艺术家和播放时间字号",
        scopes = listOf("systemui"),
        origin = "西米露 / HyperCeiler · MediaViewSize",
        license = "AGPL-3.0",
        defaultEnabled = false,
        group = ScopeFeatureGroup.CONTROL_CENTER,
        config = listOf(MediaCardSettings.titleSize, MediaCardSettings.artistSize, MediaCardSettings.timeSize),
        requirement = "使用 sp，跟随系统字体缩放；只调整通知中心普通媒体卡片，保留翻折外屏与灵动岛字号。过大的字号可能截断文字。修改后重启系统界面生效。",
    ),
    HyperFeature(
        id = "media_unlock_custom_actions",
        title = "解锁媒体卡片自定义操作",
        summary = "显示应用提供但被系统屏蔽的媒体操作",
        scopes = listOf("systemui"),
        origin = "西米露 / HyperCeiler · NewUnlockCustomActions",
        license = "AGPL-3.0",
        defaultEnabled = false,
        group = ScopeFeatureGroup.CONTROL_CENTER,
        requirement = "同时放开自定义操作图标和点击限制；不为应用添加未提供的操作，不改变播放控制参数。修改后重启系统界面生效。",
    ),
    HyperFeature(
        id = "lockscreen_third_party_biometrics",
        title = "允许第三方锁屏使用生物识别",
        summary = "放宽第三方锁屏的人脸与指纹能力判断",
        scopes = listOf("systemui"),
        origin = "西米露 / HyperCeiler · AllowThirdLockScreenUseFace",
        license = "AGPL-3.0",
        defaultEnabled = false,
        group = ScopeFeatureGroup.LOCK_SCREEN,
        requirement = "沿用上游强制报告生物识别能力的行为，可能在未录入设备上显示不可用入口；不伪造认证成功、不改变必须输入密码的策略。仅为可信锁屏开启。修改后重启系统界面生效。",
    ),
    HyperFeature(
        id = "systemui_monet_custom",
        title = "自定义莫奈主题色",
        summary = "使用指定颜色生成系统深浅色主题",
        scopes = listOf("systemui"),
        origin = "西米露 / HyperCeiler · MonetThemeOverlay",
        license = "AGPL-3.0",
        defaultEnabled = false,
        group = ScopeFeatureGroup.SYSTEM_UI_OTHER,
        config = listOf(HyperText(SYSTEM_UI_MONET_COLOR, "主题色", "输入六位十六进制颜色，留空或无效时不修改", placeholder = "#4285F4")),
        requirement = "仅覆盖生成主题时的种子色，保留系统明暗、对比度和取色风格；可与壁纸取色修复并用。修改后重启系统界面生效。",
    ),
    HyperFeature(
        id = "notification_unlock_focus",
        title = "解锁指定应用焦点通知",
        summary = "放宽选定应用的焦点通知显示限制",
        scopes = listOf("systemui"),
        origin = "西米露 / HyperCeiler · UnlockFocus",
        license = "AGPL-3.0",
        defaultEnabled = false,
        group = ScopeFeatureGroup.CONTROL_CENTER,
        config = listOf(HyperText(SYSTEM_UI_FOCUS_PACKAGES, "应用包名", "多个包名用空格、逗号或换行分隔；不支持通配符", placeholder = "com.example.app")),
        requirement = "仅影响所填包名，不为普通通知创建焦点内容；应用仍需发送兼容的焦点通知。修改后重启系统界面生效。",
    ),
    HyperFeature(
        id = "notification_disable_auto_fold",
        title = "禁止自动折叠通知",
        summary = "阻止通知自动移入不重要通知区域",
        scopes = listOf("systemui"),
        origin = "西米露 / HyperCeiler · UnimportantNotification",
        license = "AGPL-3.0",
        defaultEnabled = false,
        group = ScopeFeatureGroup.CONTROL_CENTER,
        requirement = "不删除通知、不撤回已折叠项，也不改变手动归类和隐私过滤。修改后重启系统界面生效。",
    ),
    HyperFeature(
        id = "lockscreen_hide_hint",
        title = "隐藏锁屏底部解锁提示",
        summary = "隐藏上滑、点击或按键解锁的操作提示",
        scopes = listOf("systemui"),
        origin = "西米露 / HyperCeiler · HideLockScreenHint",
        license = "AGPL-3.0",
        defaultEnabled = false,
        group = ScopeFeatureGroup.LOCK_SCREEN,
        requirement = "适用于系统默认锁屏；保留充电、设备管理、指纹错误和必须输入密码等提示。修改后重启系统界面生效。",
    ),
    HyperFeature(
        id = "control_center_auto_collapse",
        title = "点击磁贴后自动收起",
        summary = "点击可用快捷开关后收起控制中心",
        scopes = listOf("systemui"),
        origin = "西米露 / HyperCeiler · AutoCollapse",
        license = "AGPL-3.0",
        defaultEnabled = false,
        group = ScopeFeatureGroup.CONTROL_CENTER,
        requirement = "不处理编辑磁贴、不可用状态或管理员禁用的开关；不改变长按行为。修改后重启系统界面生效。",
    ),
    HyperFeature(
        id = "control_center_unlock_old",
        title = "解锁旧版控制中心",
        summary = "解除强制使用新版控制中心，遵循系统样式设置",
        scopes = listOf("systemui"),
        origin = "西米露 / HyperCeiler · ControlCenterStyle",
        license = "AGPL-3.0",
        defaultEnabled = false,
        group = ScopeFeatureGroup.CONTROL_CENTER,
        requirement = "仅解除系统界面的强制标记，不自动修改系统样式；需要系统设置提供样式入口。修改后重启系统界面生效。",
    ),
    HyperFeature(
        id = "notification_channel_settings",
        title = "通知设置跳转到通知渠道",
        summary = "从通知菜单直接打开对应渠道的设置",
        scopes = listOf("systemui"),
        origin = "西米露 / HyperCeiler · RedirectToNotificationChannelSetting",
        license = "AGPL-3.0",
        defaultEnabled = false,
        group = ScopeFeatureGroup.CONTROL_CENTER,
        requirement = "按通知 UID 选择用户；缺少渠道或无法打开时回退到应用通知设置，保留 Mi Push 特殊入口。修改后重启系统界面生效。",
    ),
    HyperFeature(
        id = "lockscreen_scramble_pin",
        title = "PIN 密码键盘乱序",
        summary = "随机排列锁屏 PIN 数字键，保持按键内容与输入一致",
        scopes = listOf("systemui"),
        origin = "西米露 / HyperCeiler · ScramblePIN",
        license = "AGPL-3.0",
        defaultEnabled = false,
        group = ScopeFeatureGroup.LOCK_SCREEN,
        requirement = "键盘视图创建时随机排列；不改密码校验，不移动紧急呼叫、删除或确认键。修改后重启系统界面生效。",
    ),
    HyperFeature(
        id = "lockscreen_double_tap",
        title = "双击锁屏空白处息屏",
        summary = "仅在锁屏状态下响应空白区域双击",
        scopes = listOf("systemui"),
        origin = "西米露 / HyperCeiler · LockScreenDoubleTapToSleep",
        license = "AGPL-3.0",
        defaultEnabled = false,
        group = ScopeFeatureGroup.LOCK_SCREEN,
        requirement = "不接管通知等控件触摸；滑动、多指与无障碍触摸探索时不息屏。修改后重启系统界面生效。",
    ),
    HyperFeature(
        id = "lockscreen_hide_zen",
        title = "隐藏锁屏勿扰提示",
        summary = "隐藏锁屏通知计数旁的勿扰提示，保留通知计数",
        scopes = listOf("systemui"),
        origin = "西米露 / HyperCeiler · HideLockscreenZenMode",
        license = "AGPL-3.0",
        defaultEnabled = false,
        group = ScopeFeatureGroup.LOCK_SCREEN,
        requirement = "适用于系统默认锁屏；不关闭勿扰模式、不改变通知过滤。修改后重启系统界面生效。",
    ),
    HyperFeature(
        id = "notification_zen_fix",
        title = "修复勿扰模式下通知提示",
        summary = "开启勿扰时抑制系统界面的通知声音、振动和提示灯",
        scopes = listOf("systemui"),
        origin = "西米露 / HyperCeiler · ZenModeFix",
        license = "AGPL-3.0",
        defaultEnabled = false,
        group = ScopeFeatureGroup.CONTROL_CENTER,
        requirement = "沿用上游行为：优先通知、仅闹钟及完全静音模式都抑制此通知提醒链，包括优先通知例外；不隐藏通知。修改后重启系统界面生效。",
    ),
    HyperFeature(
        id = "clipboard_native_overlay",
        title = "解锁原生剪贴板编辑浮窗",
        summary = "复制内容后显示 Android 原生剪贴板浮窗",
        scopes = listOf("systemui"),
        origin = "西米露 / HyperCeiler · UnlockClipboard（淡い夏 / WOMMO）",
        license = "AGPL-3.0",
        defaultEnabled = false,
        group = ScopeFeatureGroup.SYSTEM_UI_OTHER,
        requirement = "保留锁定设备、用户初始化、敏感内容和系统主动抑制检查；可能与输入法剪贴板提示同时显示。修改后重启系统界面生效。",
    ),
    HyperFeature(
        id = "lockscreen_show_notifications",
        title = "解除通知限制",
        summary = "允许更多通知在锁屏显示",
        scopes = listOf("systemui"),
        origin = "西米露 / HyperCeiler · NotificationShowOnKeyguard",
        license = "AGPL-3.0",
        defaultEnabled = false,
        group = ScopeFeatureGroup.LOCK_SCREEN,
        requirement = "可能增加锁屏可见的通知。仍保留系统的用户隐私、工作资料与敏感内容限制；修改后重启系统界面生效。",
    ),
    HyperFeature(
        id = "lockscreen_keep_notifications",
        title = "解锁后保留通知",
        summary = "解锁后保留通知，再次锁屏仍可见",
        scopes = listOf("systemui"),
        origin = "西米露 / HyperCeiler · KeepNotification（源自 XiaomiHelper）",
        license = "AGPL-3.0",
        defaultEnabled = false,
        group = ScopeFeatureGroup.LOCK_SCREEN,
        requirement = "不强制显示被应用或隐私设置隐藏的通知；修改后重启系统界面生效。",
    ),
    HyperFeature(
        id = "lockscreen_hide_status_bar",
        title = "锁屏时隐藏状态栏",
        summary = "隐藏锁屏顶部状态栏，不影响解锁后",
        scopes = listOf("systemui"),
        origin = "西米露 / HyperCeiler · HideLockScreenStatusBar",
        license = "AGPL-3.0",
        defaultEnabled = false,
        group = ScopeFeatureGroup.LOCK_SCREEN,
        requirement = "修改后重启系统界面生效。",
    ),
    HyperFeature(
        id = "lockscreen_hide_ble_toast",
        title = "禁止显示 \"已通过蓝牙设备解锁\" Toast",
        summary = "仅隐藏蓝牙解锁成功的提示",
        scopes = listOf("systemui"),
        origin = "西米露 / HyperCeiler · DisableUnlockByBleToast",
        license = "AGPL-3.0",
        defaultEnabled = false,
        group = ScopeFeatureGroup.LOCK_SCREEN,
        requirement = "不改变蓝牙解锁条件；修改后重启系统界面生效。",
    ),
    HyperFeature(
        id = "notification_mute_when_interactive",
        title = "亮屏时静音",
        summary = "亮屏时禁止通知发出提示音",
        scopes = listOf("systemui"),
        origin = "西米露 / HyperCeiler · MuteVisibleNotifications",
        license = "AGPL-3.0",
        defaultEnabled = false,
        group = ScopeFeatureGroup.CONTROL_CENTER,
        requirement = "按原功能同时抑制亮屏通知的声音、振动和提示灯；不隐藏通知。修改后重启系统界面生效。",
    ),
    HyperFeature(
        id = "notification_disable_transparent",
        title = "禁用透明模式",
        summary = "禁止横屏通知使用透明背景",
        scopes = listOf("systemui"),
        origin = "西米露 / HyperCeiler · DisableTransparent",
        license = "AGPL-3.0",
        defaultEnabled = false,
        group = ScopeFeatureGroup.CONTROL_CENTER,
        requirement = "修改后重启系统界面生效。",
    ),
    HyperFeature(
        id = "notification_freeform",
        title = "更多应用通知栏下拉打开小窗",
        summary = "放宽通知下拉打开小窗的应用限制",
        scopes = listOf("systemui"),
        origin = "西米露 / HyperCeiler · NotificationFreeform",
        license = "AGPL-3.0",
        defaultEnabled = false,
        group = ScopeFeatureGroup.SYSTEM_UI_OTHER,
        requirement = "仅处理有 Activity 跳转目标的通知；可能不支持 Mi Push 推送的通知。修改后重启系统界面生效。",
    ),
)
